name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  update-hosting:
    runs-on: ubuntu-latest
    steps:
      - name: stop gunicorn
        run: |
          cd ~/new_horizon_project; make gunicorn_stop_service 
      
      - name: start gunicorn
        run: |
          cd ~/new_horizon_project; make gunicorn_start_service 
      
      - name: âœ… done!
        run: |
          echo "âœ… done!"
